n = int(input('Digite um numero da tabuada: '))
print(f'{n} x  {1} = {n*1}')
print(f'{n} x  {2} = {n*2}')
print(f'{n} x  {3} = {n*3}')
print(f'{n} x  {4} = {n*4}')
print(f'{n} x  {5} = {n*5}')
print(f'{n} x  {6} = {n*6}')
print(f'{n} x  {7} = {n*7}')
print(f'{n} x  {8} = {n*8}')
print(f'{n} x  {9} = {n*9}')
print(f'{n} x {10} = {n*10}')

print('-'*15)
#outra forma de se fazer e dar o mesmo resultado
n = int(input('Digite um numero da tabuada: '))
print('{} x {:2} = {}'.format(n, 1, n*1))
print('{} x {:2} = {}'.format(n, 2, n*2))
print('{} x {:2} = {}'.format(n, 3, n*3))
print('{} x {:2} = {}'.format(n, 4, n*4))
print('{} x {:2} = {}'.format(n, 5, n*5))
print('{} x {:2} = {}'.format(n, 6, n*6))
print('{} x {:2} = {}'.format(n, 7, n*7))
print('{} x {:2} = {}'.format(n, 8, n*8))
print('{} x {:2} = {}'.format(n, 9, n*9))
print('{} x {:2} = {}'.format(n, 10, n*10))
